BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = single-topo/topology.json
# TOPO = linear-topo/topology.json
# TOPO = triangle-topo/topology.json

LOCAL_COMPILER = false
CPU_PORT = 255
include ../../utils/Makefile
